### ISSUE TITLE
Merge ParccVizierR and MapVizeR into same package.

### ISSUE THREAD

**Issue by hunterowens** [almartin82/parccvizieR#1]
Given that we've got an uniform body of work in these tests, would it make sense to merge the packages into a "testVizR" or something similar

**Comment by chrishaid** [comment]
I tend to think that the commons elements should be pulled out into into own commonm package altar the the other two packages then import. Keep separate things separate. That should make maintenance and development simpler.   
  
  

  
  
>

**Comment by almartin82** [comment]
I am thinking about the same thing right now at on [auto_eSD](https://github.com/almartin82/auto_eSD) - trying to figure out the right balance of common vs unified.  There doesn't seem to be any consistent cross-platform tools for working with Access databases in Python, so I'm thinking that I will:

-keep the scope of the 'official' package limited to _getting_ the file down from eSchool, so it can be cross-platform
-include a clean, sample script for unzipping and doing an Access-to-csv transform in Windows with the package
-also write a similar script for OSX/Linux, which would use different tools to open up the Access db

Thoughts?

**Comment by almartin82** [comment]
closing as

**Comment by almartin82** [comment]
bad news: closing as `wont-fix`
good news: someone (me, my team :smile:) is working on this project again!
